nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/group.name: shared-alb
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

podAnnotations: {}

podLabels: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

configMap:
  enabled: true
  name: nginx-200-conf
  data:
    default.conf: |
      server {
        listen 80;
        server_name _;
        default_type text/plain;
        location / {
          return 200 "ok\n";
        }
      }

serviceAccount:
  create: false
  name: ""

container:
  name: nginx
  ports:
    - containerPort: 80
  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 2
    periodSeconds: 5
  volumeMounts:
    - name: conf
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: default.conf

volumes:
  - name: conf
    configMap:
      name: nginx-200-conf

